name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock and Create PR
        uses: DeterminateSystems/update-flake-lock@v24
        id: update
        with:
          commit-msg: "chore(deps): update flake.lock"
          pr-labels: |
            dependencies
          sign-commits: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          token: ${{ secrets.PAT }}
      - name: Merge PR
        shell: bash
        run: gh pr merge --auto --squash "$PR_ID"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          PR_ID: ${{ steps.update.outputs.pull-request-number }}
